using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MuppavarapuStateUniversity.Models
{
    public class Course
    {   //The None option prevents values from being generated by the database automatically
      //    in cases where they would otherwise be created.Convention specifies that a property 
      //    named 'Id' with a data type of int will be configured as the primary key for an entity,
      //    and will be mapped to an Identity column in SQL Server, which automatically generates values 
      //    when data is added.If you want to implement your own value generation strategy and override the 
      //    default behaviour, you will use the None option:
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]
        public int CourseID { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; }
        [Range(0, 5)]
        public int Credits { get; set; }
        public int DepartmentID { get; set; }

        public virtual Department Department { get; set; }
        public virtual ICollection<Instructor> Instructors { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
}
}