using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MuppavarapuStateUniversity.Models
{
    public class Course
    {   //The None option prevents values from being generated by the database automatically
      //    in cases where they would otherwise be created.Convention specifies that a property 
      //    named 'Id' with a data type of int will be configured as the primary key for an entity,
      //    and will be mapped to an Identity column in SQL Server, which automatically generates values 
      //    when data is added.If you want to implement your own value generation strategy and override the 
      //    default behaviour, you will use the None option:
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int CourseID { get; set; }
    public string Title { get; set; }
    public int Credits { get; set; }

    public virtual ICollection<Enrollment> Enrollments { get; set; }
}
}